// HTML5 named character reference table (phf map generated by build.rs).
//
// The map is keyed by entity name WITHOUT the leading `&`.
// Values are slices of Unicode code points.

include!("../../generated/html5_entities.rs");
